name: AI Contribution Art

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jstrieb/github-contribution-svg@main
        with: 
          username: aijurist
          path: assets/contrib.svg
          colors: "39FF14,00F0FF,FF00E6" # AI neon colors
          shape: "neural" # AI-specific pattern
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git commit -m "Update AI contribution art"
          git push